apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-mundo-deployment
spec:
  replicas: 3  # Número de réplicas (cambia según tus necesidades)
  selector:
    matchLabels:
      app: hola-mundo
  template:
    metadata:
      labels:
        app: hola-mundo
    spec:
      containers:
      - name: hola-mundo-container
        image: carloandrepb/docker01-andres-pillajo:latest  # Reemplaza con tu imagen
        ports:
        - containerPort: 5000  # Puerto expuesto dentro del contenedor

